In [11]:
import random
import math
import sys
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split


#Hàm tính kỳ vòng. Kỳ vòng được tính bằng 1/n*sum(xi)
def mean(numbers):
    return sum(numbers) / float(len(numbers))

#Hàm tính phương sai. Phương sai được tính bằng căn bậc hai của:
# 1/(n-1)*sum(bình phương(xi-kỳ vọng))
def standard_deviation(numbers):
    avg = mean(numbers)
    variance = sum([pow(x - avg, 2) for x in numbers]) / float(len(numbers) - 1)
    return math.sqrt(variance)

#Tính dộ lệch chuẩn và phương sai cho mỗi lớp

# Tính xác suất phân phối Gaussian, dựa trên độ lệch chuẩn và phương sai 
def calculate_prob(x, mean, stdev):
    exponent = math.exp(-((x - mean) ** 2 / (2 * stdev ** 2)))
    return (1 / (math.sqrt(2 * math.pi) * stdev)) * exponent

# Du doan vector thuoc phan lop nao
def get_accuracy(value, y_test):
    correct = 0
    for i in range(len(value)):
        if value[i] == y_test[i]:
            correct += 1
    return (correct / float(len(y_test)))
   

#Ham tinh va trả về label
def calculate_label(dataset, x):
    label = dataset[:, -1]  # Nhãn của dataset
    label_values, label_counts = np.unique(label, return_counts=True)
    value = np.zeros((len(label_values), len(x)))  # Ma trận chứa xác suất cho mỗi lớp

    for i, Class in enumerate(label_values):
        sub_data = dataset[dataset[:, -1] == Class]  # Lọc dữ liệu theo lớp
        for j in range(len(x)):  # Duyệt qua các mẫu trong tập kiểm tra
            s = 1
            for k in range(x.shape[1]):  # Duyệt qua các đặc trưng của mỗi mẫu
                # Tính xác suất Gaussian cho mỗi đặc trưng
                s *= calculate_prob(x[j, k], mean(sub_data[:, k]), standard_deviation(sub_data[:, k]))
            value[i][j] = s
    return np.argmax(value, axis=0)


1. Viết hai hàm còn thiếu ở trên.

2. Load bộ dữ liệu Data_IRIS1.csv. Tách thành bộ train và bộ test.

In [12]:
df = pd.read_csv('resources/Data_IRIS1.csv')
df.head

<bound method NDFrame.head of      5.1  3.5  1.4  0.2  0
0    4.9  3.0  1.4  0.2  0
1    4.7  3.2  1.3  0.2  0
2    4.6  3.1  1.5  0.2  0
3    5.0  3.6  1.4  0.2  0
4    5.4  3.9  1.7  0.4  0
..   ...  ...  ...  ... ..
144  6.7  3.0  5.2  2.3  2
145  6.3  2.5  5.0  1.9  2
146  6.5  3.0  5.2  2.0  2
147  6.2  3.4  5.4  2.3  2
148  5.9  3.0  5.1  1.8  2

[149 rows x 5 columns]>

In [13]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

3. Gọi hàm calculate_label để dự đoán kết quả.

In [14]:
training_set = np.column_stack((X_train, y_train))

# Predict labels for the test set
predictions = calculate_label(training_set, X_test)
print(predictions)

[1 2 1 1 0 2 2 1 1 1 0 0 1 0 0 1 2 1 0 0 0 0 1 0 1 1 1 0 0 2]


4. Đánh giá phần trăm đoán đúng.

In [15]:
accuracy = get_accuracy(predictions, y_test)
print(accuracy)

0.9


5. Gọi thư viện có sẵn để so sánh kết quả.

In [20]:
from sklearn.naive_bayes import GaussianNB  
from sklearn.metrics import accuracy_score 

nb = GaussianNB()
nb.fit(X_train, y_train)
nb_predictions = nb.predict(X_test)

nb_accuracy = accuracy_score(y_test, nb_predictions)
print(nb_accuracy)

0.9


In [ ]:
import numpy as np
a=[1,2,3]
b=np.ones_like(a)
c=np.concatenate((b,a),axis=0)


array([1, 1, 1, 1, 2, 3])

In [24]:
import numpy as np 
A=np.array(['A','A','B','C','B','A','C']) 
values=np.unique(A)
values

array(['A', 'B', 'C'], dtype='<U1')

In [25]:
import numpy as np
A=np.array(['A','A','B','C','B','A','C'])
values,count=np.unique(A,return_counts=True)
count

array([3, 2, 2], dtype=int64)