Cho ma trận M và một điểm P

M=np.array([[200, 10, 1],
            [2000, 10, 1],
           [10, 2000, 0],
           [300, 10, 1],
           [400, 2000, 0],
           [20, 2000, 0],
            [10, 1000, 0],
            [300, 10, 1],
            [5, 300, 0],
            [2, 200, 0]])
P=np.array([200,10])

In [38]:
import numpy as np
import pandas as pd
M=np.array([[200, 10, 1], [2000, 10, 1], [10, 2000, 0], [300, 10, 1], [400, 2000, 0], [20, 2000, 0], [10, 1000, 0], [300, 10, 1], [5, 300, 0], [2, 200, 0]])
P=np.array([200,10])

1. Viết hàm thêm cột số 0 vào trước ma trận M

In [24]:
def add_column(M):
    M_new = np.hstack((np.zeros((M.shape[0], 1)),M))
    return M_new
M = add_column(M)
M

array([[0.e+00, 2.e+02, 1.e+01, 1.e+00],
       [0.e+00, 2.e+03, 1.e+01, 1.e+00],
       [0.e+00, 1.e+01, 2.e+03, 0.e+00],
       [0.e+00, 3.e+02, 1.e+01, 1.e+00],
       [0.e+00, 4.e+02, 2.e+03, 0.e+00],
       [0.e+00, 2.e+01, 2.e+03, 0.e+00],
       [0.e+00, 1.e+01, 1.e+03, 0.e+00],
       [0.e+00, 3.e+02, 1.e+01, 1.e+00],
       [0.e+00, 5.e+00, 3.e+02, 0.e+00],
       [0.e+00, 2.e+00, 2.e+02, 0.e+00]])

2. Viết hàm tính khoảng cách từ điểm P đếm M lưu kết quả tính được vào cột số 0 vừa thêm vào

In [25]:
def distance(M, P):
  for i in range(len(M)):
    M[i,0]=np.sqrt((M[i,1] - P[0])**2+(M[i,2]-P[1])**2)
  return M
M = distance(M, P)
M

array([[0.00000000e+00, 2.00000000e+02, 1.00000000e+01, 1.00000000e+00],
       [1.80000000e+03, 2.00000000e+03, 1.00000000e+01, 1.00000000e+00],
       [1.99904977e+03, 1.00000000e+01, 2.00000000e+03, 0.00000000e+00],
       [1.00000000e+02, 3.00000000e+02, 1.00000000e+01, 1.00000000e+00],
       [2.00002500e+03, 4.00000000e+02, 2.00000000e+03, 0.00000000e+00],
       [1.99812412e+03, 2.00000000e+01, 2.00000000e+03, 0.00000000e+00],
       [1.00806746e+03, 1.00000000e+01, 1.00000000e+03, 0.00000000e+00],
       [1.00000000e+02, 3.00000000e+02, 1.00000000e+01, 1.00000000e+00],
       [3.49463875e+02, 5.00000000e+00, 3.00000000e+02, 0.00000000e+00],
       [2.74415743e+02, 2.00000000e+00, 2.00000000e+02, 0.00000000e+00]])

3. Viết hàm sắp xếp M theo thứ tự tăng dần của cột đầu tiên (cột vừa tính được từ câu 2).

In [26]:
def sort(M):
    M = M[M[:, 0].argsort()]
    return M

M = sort(M)
M

array([[0.00000000e+00, 2.00000000e+02, 1.00000000e+01, 1.00000000e+00],
       [1.00000000e+02, 3.00000000e+02, 1.00000000e+01, 1.00000000e+00],
       [1.00000000e+02, 3.00000000e+02, 1.00000000e+01, 1.00000000e+00],
       [2.74415743e+02, 2.00000000e+00, 2.00000000e+02, 0.00000000e+00],
       [3.49463875e+02, 5.00000000e+00, 3.00000000e+02, 0.00000000e+00],
       [1.00806746e+03, 1.00000000e+01, 1.00000000e+03, 0.00000000e+00],
       [1.80000000e+03, 2.00000000e+03, 1.00000000e+01, 1.00000000e+00],
       [1.99812412e+03, 2.00000000e+01, 2.00000000e+03, 0.00000000e+00],
       [1.99904977e+03, 1.00000000e+01, 2.00000000e+03, 0.00000000e+00],
       [2.00002500e+03, 4.00000000e+02, 2.00000000e+03, 0.00000000e+00]])

4. Lấy ra 3 giá trị theo thứ tự từ trên xuống của cột cuối cùng (cột nhãn) lưu vào L

In [27]:
def get_top(L, k):
  return L[:k, -1]
get_top(M,3)

array([1., 1., 1.])

5. Viết hàm tìm giá trị xuất hiện nhiều nhất trong L. VD: L=[0,0,1,1,1,2,2,2,1,0,0,0,0] thì nhãn 0 xuất hiện nhiều nhất.

In [28]:
L=[0,0,1,1,1,2,2,2,1,0,0,0,0]
def most_frequency(L):
    unique, counts = np.unique(L, return_counts=True)
    return unique[np.argmax(counts)]
print(most_frequency(L))

0


6. Viết câu lệnh để load dữ liệu từ file Data_classification.csv.

In [29]:
df = pd.read_csv('data_classification.csv')
df.head()

4.8550642421469092  9.6399615658447146  1
0            8.625440            0.058927  0
1            3.828192            0.723199  0
2            7.150955            3.899420  1
3            6.477900            8.198181  1
4            1.922270            1.331427  0

7. Tách dữ liệu thành hai tập train (X_train) và test. Tách tập test thành X_test và y_test.

In [30]:
print(df.shape)

(99, 3)


In [31]:
X_train = df.iloc[:80,].values
test  = df.iloc[80:,].values
X_test = test[:, :-1]
y_test = test[:, -1]

# Print the shapes of the resulting datasets
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

X_train shape: (80, 3)
X_test shape: (19, 2)
y_test shape: (19,)


8. Ghép cột số 0 vào đầu X_train

In [32]:
X_train = add_column(X_train)
X_train

array([[0.        , 8.62543976, 0.05892653, 0.        ],
       [0.        , 3.82819154, 0.72319923, 0.        ],
       [0.        , 7.15095484, 3.89942042, 1.        ],
       [0.        , 6.47790044, 8.19818055, 1.        ],
       [0.        , 1.9222695 , 1.33142726, 0.        ],
       [0.        , 8.97821589, 0.99343751, 1.        ],
       [0.        , 6.63560308, 8.54280268, 1.        ],
       [0.        , 7.67235895, 5.41639979, 1.        ],
       [0.        , 4.86601533, 2.04267129, 0.        ],
       [0.        , 6.86140497, 9.65530972, 1.        ],
       [0.        , 8.54042132, 2.59037423, 1.        ],
       [0.        , 3.71788065, 5.38166211, 0.        ],
       [0.        , 9.18129712, 0.17147465, 1.        ],
       [0.        , 9.56014002, 0.02494649, 0.        ],
       [0.        , 5.97136947, 4.18830187, 1.        ],
       [0.        , 9.43820269, 1.94381244, 1.        ],
       [0.        , 4.35755102, 9.88798331, 1.        ],
       [0.        , 4.54033196,

9. Duyệt qua từng điểm dữ liệu của X_test:

    9.1 Tính khoảng cách đến tất cả các điểm của X_train

    9.2 Sắp xếp X_train theo thứ tự tăng dần của cột đầu tiên.

    9.3 Lấy ra k theo thứ tự từ trên xuống của cột nhãn. (k là một số lẻ: 3, 7, 9)

    9.4 Xác nhãn xuất hiện nhiều nhất
    
Lưu tất cả nhãn tìm được vào Lable.

In [33]:
def KNN(X_train,X_test,k = 3):
  Lable =[]
  for i in X_test:
    #9.1: Tính khoảng cách đến tất cả các điểm của X_train
    distances = distance(X_train, i)
    #9.2: Sắp xếp X_traint theo thứ tự tăng dần của cột đầu tiên.
    sorted = sort(distances)
    #9.3: Lấy ra K theo thứ tự từ trên xuống của cột nhãn
    top_k = get_top(sorted,k)
    #9.4: Nhãn xuất hiện nhiều nhất
    l = most_frequency(top_k)
    Lable.append(l)
  return Lable
Lable = KNN(X_train,X_test,3)
y_test

array([1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0.,
       1., 0.])

10. So sánh y_test và Lable để đánh giá tỉ lệ phần trăm đoán đúng.

In [34]:
def accuracy(y_test, lables):
  return np.mean(y_test == lables)
kq = accuracy(y_test, Lable)
print(f"Accuracy: {kq:.2f}")


Accuracy: 0.95


11. Sử dụng thư viện về KNN để train và test

In [37]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,:-1], df.iloc[:,-1], test_size=0.2, random_state=42)
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.85


12. Tổ chức các hàm đã viết thành lớp lấy tên là KNN_Ten_Ban

In [ ]:
class KNN_Nhung:
  def __init__(self, k=3):
    self.k = k
  def add_zeros(self, M):
    M = np.hstack((np.zeros((M.shape[0], 1)),M))
    return M
  def sort(self, M):
    M = M[M[:, 0].argsort()]
    return M
  def most_frequency(self, L):
    unique, counts = np.unique(L, return_counts=True)
    return unique[np.argmax(counts)]
  def get_top(self, L, k):
    return L[:k, -1]
  def predict(self, X_train,X_test):
    X_train = self.add_zeros(X_train)
    Lable =[]
    for i in X_test:
      distances = self.distance(X_train.copy(), i)
      sorted_distances = self.sort(distances)
      top_k = self.get_top(sorted_distances, self.k)
      label = self.most_frequency(top_k)
      Lable.append(label)
      return Lable
  def accuracy(self, y_test, labels):
        return np.mean(y_test == labels)