Tạo ma trận A=[[1,4,2],
              [2,3,4],
              [7,5,1]]


1.1.	Viết câu lệnh để tìm MAX theo cột của A. Kết qua như sau: [[7 5 4]]

In [ ]:
import numpy as np
a=np.array([[1,4,2], [2,3,4], [7,5,1]])
a

1.2.	Viết cây lệnh để tìm MIN theo cột của A. Kết quả là: 

1.3 Viết câu lệnh để in ra vị trí lớn nhất trên mỗi hàng

1.4. In ra dòng thứ 2

1.5. In ra cột thứ nhất và cột thứ nhì

1.6. So sánh giá trị ở dòng 0 và dòng số 1

In [ ]:
import numpy as np
aa=np.array([1,2,3])
bb=np.array([1,2,3])
np.array_equal(aa,bb)

True

1.7. Tính tổng theo mỗi hàng trong trong ma trận A

1.8. Viết câu lệnh hiển thị kích thước ma trận A

1.9. x = np.array([[1, 3], [4, 4], [4, 2]]) chuyển x qua ma trận có kích thước (2x3)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

1.10. Viết câu lệnh để nhân các phần tử của x và y tương ứng với nhau
x=np.array([[1, 2, 3], [1, 3, 4]])
y = np.array([[0, 3, 1], [4, 1, 1]]) 

1.11. Viết câu lệnh để nhân hai ma trận với nhau
x = np.array([[1, 2], [1, 0]])
y = np.array([[0, 3, 1], [1, 3, 0]])

1.12. Tạo ma trận zero có số chiều là 2x3

In [ ]:
tt1=np.ones((1,2))
tt1

array([[1., 1.]])

1.13. Tạo ma trận có số chiều 3x4 với các số ngẫu nhiên.
Dùng hàm randn trong numpy

1.14. Tạo ra dãy số ngẫu nhiên không trùng lặp từ 1 đến n. Với n cho trước. 
Gợi ý: Dùng hàm permutation trong numpy

array([2, 6, 8, 7, 4, 0, 9, 1, 3, 5])

1.15. Viết câu lệnh để tạo ma trân 3 hàng 1 cột.
Gợi ý: Dùng hàm ones.

1.16. Chèn thêm cột chứa các số 1 vào ma trận A ở trên.
Gợi ý: Dùng hàm vstack hoặc dùng concatenate/hstack trong numpy

1.17. Các câu lệnh để tính tổng, tìm max các phần tử trên đường chéo chính của ma trận A. 
Gợi ý: Dùng diagonal

In [ ]:
a

1.18. Cho vector sau: y_pred = np.array([0, 1, 0, 2, 1, 1, 0, 2, 1, 2]) Viết câu lệnh để cho biết có bao nhiêu giá trị và số lần xuất hiện của nó. 
Gợi ý: Dùng unique với return_counts=True


1.19. Cho kết quả dự đoán và kết quả thực tế như sau:
y_true = np.array([0, 0, 0, 0, 1, 1, 1, 2, 2, 2])
y_pred = np.array([0, 1, 0, 2, 1, 1, 0, 2, 1, 2])
Viết hàm đánh giá tỉ lệ phần trăm đoán đúng.

1.20. Cho kết quả dự đoán và kết quả thực tế như sau: y_true = np.array([0, 0, 0, 0, 1, 1, 1, 2, 2, 2]) y_pred = np.array([0, 1, 0, 2, 1, 1, 0, 2, 1, 2])
Viết câu lệnh để tạo ra ma trận Confusion matrix để đánh giá mô hình
Gợi ý: Dùng vòng lặp sau:
  for n in range(y_true.shape[0]):
        cm[y_true[n], y_pred[n]] += 1
