Tạo ma trận A=[[1,4,2],
              [2,3,4],
              [7,5,1]]


1.1.	Viết câu lệnh để tìm MAX theo cột của A. Kết qua như sau: [[7 5 4]]

In [1]:
import numpy as np
a=np.array([[1,4,2], [2,3,4], [7,5,1]])
a

array([[1, 4, 2],
       [2, 3, 4],
       [7, 5, 1]])

In [2]:
Max=np.max(a,axis=0)
Max

array([7, 5, 4])

1.2.	Viết cây lệnh để tìm MIN theo cột của A. Kết quả là:

In [3]:
Min=np.min(a,axis=0)
Min

array([1, 3, 1])

1.3 Viết câu lệnh để in ra vị trí lớn nhất trên mỗi hàng

In [6]:
Max_line = np.argmax(a,axis=1)
Max_line

array([1, 2, 0])

1.4. In ra dòng thứ 2

In [7]:
np.array(a[1])

array([2, 3, 4])

1.5. In ra cột thứ nhất và cột thứ nhì

In [8]:
np.array(a[:,:2])

array([[1, 4],
       [2, 3],
       [7, 5]])

1.6. So sánh giá trị ở dòng 0 và dòng số 1

In [ ]:
import numpy as np
aa=np.array([1,2,3])
bb=np.array([1,2,3])
np.array_equal(aa,bb)

True

In [9]:
np.array_equal(a[0],a[1])

False

1.7. Tính tổng theo mỗi hàng trong trong ma trận A

In [22]:
tong = np.sum(a,axis=1)
print(tong)

[ 7  9 13]


1.8. Viết câu lệnh hiển thị kích thước ma trận A

In [11]:
a.shape

(3, 3)

1.9. x = np.array([[1, 3], [4, 4], [4, 2]]) chuyển x qua ma trận có kích thước (2x3)

In [53]:
x = np.array([[1, 3], [4, 4], [4, 2]])
print(x)

[[1 3]
 [4 4]
 [4 2]]


In [54]:
x_trans=np.reshape(x,(2,3))
print(x_trans)

[[1 3 4]
 [4 4 2]]


1.10. Viết câu lệnh để nhân các phần tử của x và y tương ứng với nhau
x=np.array([[1, 2, 3], [1, 3, 4]])
y = np.array([[0, 3, 1], [4, 1, 1]])

In [19]:
x=np.array([[1, 2, 3], [1, 3, 4]])
y = np.array([[0, 3, 1], [4, 1, 1]])
mul =np.multiply(x,y)
print(mul)

[[0 6 3]
 [4 3 4]]


1.11. Viết câu lệnh để nhân hai ma trận với nhau
x = np.array([[1, 2], [1, 0]])
y = np.array([[0, 3, 1], [1, 3, 0]])

In [25]:
x = np.array([[1, 2], [1, 0]])
y = np.array([[0, 3, 1], [1, 3, 0]])
tich = np.dot(x,y)
print(f"Tích của hai ma trận là : \n{tich}")

Tích của hai ma trận là : 
[[2 9 1]
 [0 3 1]]


1.12. Tạo ma trận zero có số chiều là 2x3

In [27]:
tt1=np.zeros((2,3))
print(tt1)

[[0. 0. 0.]
 [0. 0. 0.]]


1.13. Tạo ma trận có số chiều 3x4 với các số ngẫu nhiên.
Dùng hàm randn trong numpy

In [28]:
nn=np.random.randn(3,4)
print(nn)

[[-0.13381464 -0.12029831 -1.5881022  -1.49075789]
 [-0.79583701  0.99315047  0.01192805  0.55294557]
 [-0.9755418   0.75782582  0.41608985 -0.7238905 ]]


1.14. Tạo ra dãy số ngẫu nhiên không trùng lặp từ 1 đến n. Với n cho trước.
Gợi ý: Dùng hàm permutation trong numpy

In [29]:
mm = np.random.permutation(10)
print(mm)

[6 2 4 5 8 0 1 7 3 9]


1.15. Viết câu lệnh để tạo ma trân 3 hàng 1 cột.
Gợi ý: Dùng hàm ones.

In [32]:
A = np.ones((3,1))
print(A)

[[1.]
 [1.]
 [1.]]


1.16. Chèn thêm cột chứa các số 1 vào ma trận A ở trên.
Gợi ý: Dùng hàm vstack hoặc dùng concatenate/hstack trong numpy

In [33]:
chen = np.hstack((a,A))
print(chen)

[[1. 4. 2. 1.]
 [2. 3. 4. 1.]
 [7. 5. 1. 1.]]


1.17. Các câu lệnh để tính tổng, tìm max các phần tử trên đường chéo chính của ma trận A.
Gợi ý: Dùng diagonal

In [37]:
np.sum(np.diagonal(a))

5

In [38]:
np.max(np.diagonal(a))

3

1.18. Cho vector sau: y_pred = np.array([0, 1, 0, 2, 1, 1, 0, 2, 1, 2]) Viết câu lệnh để cho biết có bao nhiêu giá trị và số lần xuất hiện của nó.
Gợi ý: Dùng unique với return_counts=True


In [41]:
y_pred = np.array([0, 1, 0, 2, 1, 1, 0, 2, 1, 2])
a,b=np.unique(y_pred,return_counts=True)
print(f"Vecto có các giá trị sau: \n {a}")
print(f"Số lần xuất hiện tương ứng của các giá trị: \n {b}")

Vecto có các giá trị sau: 
 [0 1 2]
Số lần xuất hiện tương ứng của các giá trị: 
 [3 4 3]


1.19. Cho kết quả dự đoán và kết quả thực tế như sau:
y_true = np.array([0, 0, 0, 0, 1, 1, 1, 2, 2, 2])
y_pred = np.array([0, 1, 0, 2, 1, 1, 0, 2, 1, 2])
Viết hàm đánh giá tỉ lệ phần trăm đoán đúng.

In [49]:
y_true = np.array([0, 0, 0, 0, 1, 1, 1, 2, 2, 2])
y_pred = np.array([0, 1, 0, 2, 1, 1, 0, 2, 1, 2])
kp = (y_true==y_pred).mean()
print(f"Tỉ lệ phần trăm đoán đúng là: {kp}")

Tỉ lệ phần trăm đoán đúng là: 0.6


1.20. Cho kết quả dự đoán và kết quả thực tế như sau: y_true = np.array([0, 0, 0, 0, 1, 1, 1, 2, 2, 2]) y_pred = np.array([0, 1, 0, 2, 1, 1, 0, 2, 1, 2])
Viết câu lệnh để tạo ra ma trận Confusion matrix để đánh giá mô hình
Gợi ý: Dùng vòng lặp sau:
  for n in range(y_true.shape[0]):
        cm[y_true[n], y_pred[n]] += 1


In [4]:
y_true = np.array([0, 0, 0, 0, 1, 1, 1, 2, 2, 2])
y_pred = np.array([0, 1, 0, 2, 1, 1, 0, 2, 1, 2])
cm = np.zeros((3,3))
for n in range(y_true.shape[0]):
  cm[y_true[n], y_pred[n]] += 1
print(f"Ma trận Confusion matrix là: \n {cm}")


Ma trận Confusion matrix là: 
 [[2. 1. 1.]
 [1. 2. 0.]
 [0. 1. 2.]]
